const SpotifyWebApi = require('spotify-web-api-node');
const storedAccessToken = require('./server.js');

const spotifyController = new SpotifyWebApi({
    clientId: 'client id goes here',
    clientSecret: 'client secret goes here',
    redirectUri: 'http://www.example.com/callback'
});

spotifyController.setAccessToken('<your_access_token');

const playlistName = ''; //-> Name of your playlist
const artistNames = []; //-> array of artist names that the user types in
const artistIds = [];

spotifyController.createPlaylist(playlistName, { 'description': 'Auto-Generated by FestivalPLG', 'public': true }) //-> the first parameter here needs to be the title of the playlist
  .then(function(data) {
    // need to store the playlist id somewhere
    // console.log('Created playlist!');
  }, function(err) {
    console.log('Something went wrong!', err);
  });

spotifyController.searchArtists([...artistNames]) //-> this parameter is an array of the artist names that the user types in ***to spread or not to spread???***
  .then(function(data) {
    
    // console.log('Search by "Love"', data.body);
  }, function(err) {
    console.error(err);
  });

spotifyController.getArtistTopTracks([...artistIds], 'US') //-> The first parameter is the artist ID. The second parameter here is the 'region'. Keep it as 'US'.
  .then(function(data) {
    console.log(data.body);
    }, function(err) {
    console.log('Something went wrong!', err);
  });

spotifyController.addTracksToPlaylist(playlistId, ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "spotify:track:1301WleyT98MSxVHPZCA6M"])
  .then(function(data) {
    console.log('Added tracks to playlist!');
  }, function(err) {
    console.log('Something went wrong!', err);
  });