const SpotifyWebApi = require('spotify-web-api-node');
const cookieParser = require('cookie-parser');
const server = require('./server');
const spotifyController = new SpotifyWebApi({ //-> docs say that credentials are optional??
    // clientId: 'client id goes here',
    // clientSecret: 'client secret goes here',
    // redirectUri: 'http://www.example.com/callback'
});

// console.log('REQUEST.COOKIES***`***', req.Cookies);
// const storedAccessToken;

// console.log('STORED ACCESS TOKEN ON LINE 13 OF NEWCONTROLLERS', token)

// spotifyController.setAccessToken(storedAccessToken);

// const playlistName = ''; //-> Name of your playlist
// const artistNames = ['artist:name', 'artist:name', 'artist:name']; //-> array of artist names that the user types in
// const artistIds = [];
// const playlistId = localStorage.getItem('playlistID');

// BQC0LC9I-sLjbX5iA6A_DFJtO78AvW66hlZAx13xOD0aSZHg5sSpIZDaTvbZ-OVqdq4xsGbiyY_y_GBl_HceN3sNeVervCjfn2ZTD4-XIR1zfYijnwGhq-YWKmq-EU3SqhYO43wRnKHELtE50d3Voj1zYogXQE1ysJHxYwk3Wtp1kWwmJfaY5xpIGmFhnQiKCgyC2V4uKp0ivMouDYc1JNc

spotifyController.cookieFinder = (req, res, next) => {
  // console.log('REQUEST OBJECT IN COOKIE FINDER', req);
  // console.log('RESPONSE OBJECT IN COOKIE FINDER', res);
  // spotifyController.setAccessToken(req.cookies.spotify_auth_state);
  return next();
  // .then(data => {return next()})
};

spotifyController.newMiddleware = (req, res, next) => {
  console.log('RES.LOCALS.TOKEN LINE 34******',res.locals.token);
  spotifyController.setAccessToken(res.locals.token);
  return next();
}

spotifyController.createPlaylist('test name3', { 'description': 'Auto-Generated by FestivalPLG', 'public': true }) //-> the first parameter here needs to be the title of the playlist
  .then(function(data) {
    console.log(data.body.id);
    // console.log('REQUEST.COOKIES******', req.Cookies);
    // localStorage.setItem('playlistID', data.body.id); //-> should store the playlist ID in local storage
  }, function(err) {
    console.log('Something went wrong!', err);
  });

// spotifyController.searchArtists([...artistNames]) //-> format: ('artist:name') this parameter is an array of the artist names that the user types in ***to spread or not to spread???***
//   .then(function(data) {
//     return data.body.artists.items.map(el => el.id);
//   }, function(err) {
//     console.error(err);
//   });

// spotifyController.getArtistTopTracks([...artistIds], 'US') //-> The first parameter is the artist ID(s). The second parameter here is the 'region'. Keep it as 'US'.
//   .then(function(data) {
//     return data.body.tracks.map(el => el.uri);
//     }, function(err) {
//     console.log('Something went wrong!', err);
//   });

// spotifyController.addTracksToPlaylist(localStorage.getItem('playlistID'), ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "spotify:track:1301WleyT98MSxVHPZCA6M"]) //-> this first parameter grabs the playlistID from local storage
//   .then(function(data) {
//     // console.log('Added tracks to playlist!');
//   }, function(err) {
//     console.log('Something went wrong!', err);
//   });

  module.exports = spotifyController;